### ISSUE TITLE
No mana symbols

### ISSUE THREAD

**Issue by HMPoweredMan** [ndepaola/mtg-autoproxy#1]
I can't seem to find the mana symbol font which is stated to be included in the repo.

**Comment by HMPoweredMan** [comment]
I attempted to replace the Generate Mana cost scripts with the MTG2016 font found in an earlier repo since the custom font is not included, but it does not turn out correctly.

<img width="1344" alt="Terminate" src="https://user-images.githubusercontent.com/9319502/61151740-a4f37d00-a4b4-11e9-8b3d-914ebd7534a3.png">

Colored mana symbols appear to overlap and justification is wrong. Additionally the mana symbol within the circle is scaled incorrectly

<img width="1344" alt="Miscalculation" src="https://user-images.githubusercontent.com/9319502/61151891-fbf95200-a4b4-11e9-8f43-2600eec455da.png">

**Comment by ndepaola** [comment]
Sorry about this - I could have sworn I uploaded it. Please find it in the repo now.

Good to see the rest of the system seems to be working for you though!

**Comment by HMPoweredMan** [comment]
Works perfectly now thank you! Great project!
