### ISSUE TITLE
Borderify Broken Using Newest Templates

### ISSUE THREAD

**Issue by duxprime** [ndepaola/mtg-autoproxy#10]
I pulled the latest changes from the repo and updated the automated templates to match. Using `borderifyAll.jsx`, my borderified output is now looking like this:

![image](https://user-images.githubusercontent.com/2328035/71682022-70be9200-2d5c-11ea-94f0-20472b29fd53.png)

This is for a render that started like this: 
![image](https://user-images.githubusercontent.com/2328035/71682077-951a6e80-2d5c-11ea-8a41-92b0d61757ea.png)

I'm using:
PhotoShop CS6
Windows 10

**Comment by ndepaola** [comment]
could you try changing the value of 'artScaleFactor` in 'excessFunctions' from 100 to 50, then see if that makes a difference? I suspect this is the same bug that causes art to be twice as large when inserted into the card frame. Though if artwork is sized correctly and borderified cards are twice as large as they should be, then I'm not sure what could cause that discrepancy

**Comment by duxprime** [comment]
It was already  `artScaleFactor = 50`. I tried changing it to 25, and the render comes out like: 
![image](https://user-images.githubusercontent.com/2328035/71743237-1263e300-2e32-11ea-86bd-1d655c776449.png)

FWIW, this was working just fine before pulling the latest changes.

**Comment by HMPoweredMan** [comment]
Same issue in the classic branch

**Comment by HMPoweredMan** [comment]
The image height and width need to specify pixels. They may be defaulted to inches for most people.
Adding back .as("px") for all bounds should do the trick. Scale factor back to 100
You can replace the function "frame" in excessFunctions with this:

```
function frame(leftPix, topPix, rightPix, bottomPix) {
  var docRef = app.activeDocument;
  // Get width and height of image
  var imageHeight = bottomPix - topPix;
  var imageWidth = rightPix - leftPix;
        
  // Get current size of window
  var myLayer = docRef.layers.getByName("Layer 1");
  var windowHeight = myLayer.bounds[3].as("px") - myLayer.bounds[1].as("px");
  var windowWidth = myLayer.bounds[2].as("px") - myLayer.bounds[0].as("px");  

  // Determine how much to scale the art by, such that it fits into the art window
 var percentageToScale = artScaleFactor * (Math.max(imageWidth / windowWidth, imageHeight / windowHeight));
  myLayer.resize(percentageToScale, percentageToScale, AnchorPosition.TOPLEFT);
  myLayer.move(activeDocument, ElementPlacement.PLACEATEND);
```

I renamed some variables (swapping image and window) because the current naming was confusing to me but the important part is the addition of .as("px") on the bounds which makes it no longer required in the line:

` var percentageToScale = artScaleFactor * (Math.max(imageWidth / windowWidth, imageHeight / windowHeight));`

**Comment by duxprime** [comment]
This did it for me. Thanks, Kyle!
___
One thing to note for others looking to fix this: I didn't replace the entire `frame()` function with this implementation. Using the @HMPoweredMan's function wholesale didn't work for me in CS6.

I used the existing implementation and simply converted to pixels.
```
  var imageHeight = myLayer.bounds[3].as("px") - myLayer.bounds[1].as("px");
  var imageWidth = myLayer.bounds[2].as("px") - myLayer.bounds[0].as("px");

 var percentageToScale = artScaleFactor * (Math.max(windowWidth / imageWidth, windowHeight / imageHeight));
```

**Comment by duxprime** [comment]
I created a PR to fix this. #11
