### ISSUE TITLE
Misaligned mana cost

### ISSUE THREAD

**Issue by hunz-dev** [ndepaola/mtg-autoproxy#14]
First off, just wanted to say what a great tool this is! Thanks for sharing it with the community.

I'm running into a slight issue where the mana cost is misaligned when running the main proxy script. I was curious if you had any ideas on what might be causing this?

I'm running this on Windows 10 with Photoshop CS6 if that helps!

![image](https://user-images.githubusercontent.com/6790154/77249805-aa8f8e00-6c11-11ea-9217-4a2136a8b71e.png)

**Comment by hunz-dev** [comment]
I noticed that after the `proxy.jsx` script ran, the text field containing the mana cost switched the justification from right to left. I can't say for sure what is causing it, but by adding a line to force the justification back to right, it aligns just fine.

https://github.com/hunz-dev/mtg-autoproxy/blob/set-symbols/scripts/proxy.jsx#L565

 I'm not sure if this is the right solution, but if you'd like I can make a PR.

**Comment by ndepaola** [comment]
glad to hear this was a simple fix! I've added your solution to the most recent commit

**Comment by ImperatorJulius** [comment]
I have the same issue, but also with the name of the card and card type. By changing Justification.RIGHT to Justification.LEFT for the mana cost seems to work. See issue #21
