### ISSUE TITLE
Zendikar MDFC Templates

### ISSUE THREAD

**Issue by mwerner96** [ndepaola/mtg-autoproxy#23]
Hi, I wanted to make some proxies for the new Zendikar MDFCs so I wouldn't have to pull the cards out of their sleeves all the time. I tried to make them manually with your tf-templates but I got stuck on the MDFC-indicator in the top left. It seems like you have already made some MDFC-Proxies. Could you please upload your new templates on Google Drive? Cheers!

**Comment by ndepaola** [comment]
the current full art MDFC template was kinda hacked together so it's not ready to be released yet, sorry! I also don't have a normal style MDFC template to work with autoproxy yet but it's on the todo list

**Comment by ndepaola** [comment]
mdfc templates now available on my gdrive
