### ISSUE TITLE
Error 23: ) does not have a value. Line 1

### ISSUE THREAD

**Issue by joegumby** [ndepaola/mtg-autoproxy#24]
Edit: Never mind, I tried it again and it works now, I don't think I did anything though.

I tried the fixes for this but I'm on windows and the chmod fix seems to be a mac thing.
I know very little about coding so that doesn't help, it could be a simple fix that I don't know about.
Can anyone help?

Windows 10 Pro 20H2

Photoshop 22.0.1

Python 3.9

**Comment by ndepaola** [comment]
https://github.com/ndepaola/mtg-autoproxy/issues/27
