### ISSUE TITLE
[Feature request] Automatically load artist names

### ISSUE THREAD

**Issue by FlorisWarmenhoven** [ndepaola/mtg-autoproxy#5]
Hi bud,

I was wondering if you could integrate functionality for the Python script to automatically get the artist name and put it on the card.

This will probably need to be an optional flag, I imagine plenty of people use alternative art work.
Perhaps you could do it as a fallback, i.e: if there is no `(artist name)` found on the image file name, use the artist from the scryfall API.

I dug through the docs, and found this:
https://scryfall.com/docs/api/cards
Under 'print fields' it shows artist. 

Think this is something implementable?

**Comment by ndepaola** [comment]
Hey hey,

I think that should be doable - I'll have a crack at it tonight & add it to the next commit :)

**Comment by ndepaola** [comment]
This is in the new commit - I implemented it as a fallback for when no artist is included in the filename. Let me know how it works for you and I'll close this thread :)

**Comment by ndepaola** [comment]
closing this thread - let me know if you have any issues with this feature. It's worked as expected in my testing

**Comment by FlorisWarmenhoven** [comment]
Awesome. Sorry dude, been swamped at work. Haven't had time to test. :(
