### ISSUE TITLE
Issue: resolving artist font to custom NDPMTG font results in weird text

### ISSUE THREAD

**Issue by FlorisWarmenhoven** [ndepaola/mtg-autoproxy#8]
Hi there,

I downloaded all the fonts as described. When running the `proxyAll` script, a message popped up that the MTG2016 font could not be resolved. I checked your FAQ and followed the steps. I opened up the `normal.psd` and resolved the Artist font (which was showing an error) to the `NDPMTG` font. This is then the text at the bottom of the card:

![image](https://user-images.githubusercontent.com/15650071/71322775-9a112f80-24cb-11ea-8e6f-45f0ba1dec78.png)

What am I doing wrong?

**Comment by FlorisWarmenhoven** [comment]
Not resolving it results in text like this:

![image](https://user-images.githubusercontent.com/15650071/71322967-23c1fc80-24ce-11ea-8e65-4a52de468163.png)

**Comment by ndepaola** [comment]
ah, I think what's going on when it resolves the missing font is it makes the entire text layer that font, not just the one character with the missing font. 

I'll update my templates shortly to resolve this fully, but in the meantime, you can open up the template, opt to not resolve the font, then select the `a` character and change that character to the NDPMTG font, and save & close the template (make sure you select the empty `Layer 1` layer before saving). 

Sorry about this!

**Comment by FlorisWarmenhoven** [comment]
No need to be sorry. I'm really happy you're so on top of this!

**Comment by ndepaola** [comment]
forgot to close this issue until now, but this should be resolved for all templates
